### PR TITLE
Always assume python bytes type IF not PILImage or np.ndarray

### PR DESCRIPTION
**Pull request by syaifulnizamyahya**
When working with pythonnet in c#, we can't provide python bytes types.  Although this will fix the call from C#, not sure about other scenario.

### CODE REVIEW

**Comment by syaifulnizamyahya** [comment]
@danielgatis If you want, I can provide simple example complete with python virtual environment configured for pythonnet

**Comment by syaifulnizamyahya** [comment]
Another idea is a parameter to force remove function to assume the type is python bytes.
Eg. remove(input, assume_bytes = true)

**Comment by danielgatis** [comment]
> Another idea is a parameter to force remove function to assume the type is python bytes. Eg. remove(input, assume_bytes = true)

I think this path is perfect.
This way we maintain compatibility with old versions.

**Comment by syaifulnizamyahya** [comment]
https://github.com/danielgatis/rembg/pull/663

**Pull request closed without merging**
