### PR TITLE
Add BiRefNet-General and BiRefNet-Portrait models as available models

### PR DESCRIPTION
**Pull request by dimitribarbot**
I'm following a suggestion to include [BiRefNet](https://github.com/ZhengPeng7/BiRefNet) as available models in the [Stable Diffusion WebUI Rembg extension](https://github.com/AUTOMATIC1111/stable-diffusion-webui-rembg) which is using your project as a library: https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/16033.

As the BiRefNet creator has uploaded ONNX model files, I propose this Pull Request to enable BiRefNet General and BiRefNet Portrait as available models.

Also, please note that I've put these kinds of TODO in the 2 session files as you may want to upload the ONNX files in your repository instead of using those of BiRefNet:
```
# TODO:
# - Change this url to https://github.com/danielgatis/rembg/releases/download/v0.0.0/birefnet-general.onnx if needed
# - Then replace below sha256 with md5 checksum
# - And update url in README file
```

### CODE REVIEW

**Comment by yo1nkers** [comment]
I'm very for this suggestion, as a user of BiRefNet myself I'd love to break away from the huggingface cloud inference and see BiRefNet usable in a more user friendly UI.

I'd also suggest to add the other weights of BiRefNet, **General-Lite, DIS, COD** & **HRSOD**, to be added if the pull request is looked at and further developed

**Comment by danielgatis** [comment]
@dimitribarbot Wow 😮! 

Thank you so much for your PR. To keep the models stored in the same place, I uploaded the files to this repo. Can you please modify your code to use these models?

https://github.com/danielgatis/rembg/releases/download/v0.0.0/BiRefNet-general-epoch_244.onnx
https://github.com/danielgatis/rembg/releases/download/v0.0.0/BiRefNet-portrait-epoch_150.onnx

**Comment by yo1nkers** [comment]
> @dimitribarbot Wow 😮!
> 
> Thank you so much for your PR. To keep the models stored in the same place, I uploaded the files to this repo. Can you please modify your code to use these models?
> 
> https://github.com/danielgatis/rembg/releases/download/v0.0.0/BiRefNet-general-epoch_244.onnx https://github.com/danielgatis/rembg/releases/download/v0.0.0/BiRefNet-portrait-epoch_150.onnx

I'm so hype for this. Will be the best RemBG addition in a long time. Really will be happy to be using BiRefNet in the RemBG extension for Auto1111.

As perhaps a suggestion, maybe add a checkbox for classic and BiRefNet models?

**Comment by danielgatis** [comment]
@dimitribarbot Yeah, feel free to open more PRs :). I will add you as a project collaborator.

**Comment by danielgatis** [comment]
all good, perfect! Thank you so much!

**Comment by yo1nkers** [comment]
Hopefully Automatic sees this. Amazing work Dimitri, a service to us all.

**Comment by danielgatis** [comment]
@dimitribarbot yeah, i think it is a good idea to use the `pooch.create` function. But my concern now is how long the tests will take. Do these new models run fast using only the CPU?

**Comment by danielgatis** [comment]
@dimitribarbot solved! https://github.com/danielgatis/rembg/commit/95b81143c9a1d760c892ffa7f406f055fc244b81

Thank you so much

**Pull request merged**
